### ISSUE TITLE
Every time I open a new window, I get two really old (read) notifications.

### ISSUE THREAD

**Issue by jsg2021** [Axosoft/atom-github-notifications#11]
I get new notifications and they go away after dismissing, but I have two notifications that are over a week old that keep coming back every time I open a new atom window. Its like they're stuck in a cache locally.

**Comment by eode** [comment]
Confirmed.  Same behavior.

**Comment by jsg2021** [comment]
Closing because I don't use this plugin anymore and it doesn't look like this plugin has been updated in some time.
